[user]
	name = raaowx
	email = raaowx@protonmail.com
[core]
	editor = nano
	excludesfile = ~/.gitignore_global
	fsmonitor = true
	untrackedCache = true
	protectHFS = true
	protectNTFS = true
[transfer]
	fsckObjects = true
[init]
	defaultBranch = master
[pull]
	rebase = true
[push]
	autoSetupRemote = true
	followTags = true
[fetch]
	prune = true
	pruneTags = false
[rebase]
	autoStash = true
[rerere]
	enabled = true
[merge]
	conflictStyle = zdiff3
[log]
	date = iso
[column]
	ui = auto
[branch]
	sort = refname
[tag]
	sort = version:refname
[diff]
	algorithm = histogram
	colorMoved = zebra
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
